apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: springcloudgateways.tanzu.vmware.com
spec:
  group: tanzu.vmware.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                routes:
                  type: object
  scope: Namespaced
  names:
    plural: springcloudgateways
    singular: springcloudgateway
    kind: SpringCloudGateway
    shortNames:
      - scg
      - scgs
